### ISSUE TITLE
WinError 10061 when attempting to use omphudsexy

### ISSUE THREAD

**Issue by MaxOhNoo** [fionafibration/team-frotress-2#10]
The program works fine without the hud, but once I add omphudsexy to my custom folder, doing the main menu confirmation provides the following:

```rescript
Wait until TF2 has made it to the main menu, then press enter

Traceback (most recent call last):
  File "c:\Users\Max\Downloads\team-frotress-2-main\team-frotress-2-main\main.py", line 266, in <module>
    rcon.connect()
  File "C:\Users\Max\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\valve\rcon.py", line 464, in wrapper
    return function(instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Max\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\valve\rcon.py", line 464, in wrapper
    return function(instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Max\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\valve\rcon.py", line 483, in connect
    self._socket.connect(self._address)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
``` 

This is my config.py:

```rescript
TF2_GAME_EXECUTABLE = "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Team Fortress 2\\tf_win64.exe"
TF2_CONSOLE_LOG = "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Team Fortress 2\\tf\\console.log"
TF2_EXTRA_LAUNCH_OPTIONS = "-novid -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars -noquicktime"

INTIFACE_SERVER_ADDR = "ws://127.0.0.1:12345"  # The address intiface central is listening on

RCON_PORT = 2541  # Change if you have another port interfering

# Binds custom weapon switching functionality to track weapon changes
ENABLE_WEAPONSWITCH = True

UPDATE_SPEED = 5  # Speed in updates per second, values higher than 10 are not recommended for performance

BASE_VIBE = 0.0  # Base vibration speed that motor will always be on

ACTIVATE_COMMAND = ""  # TF2 console command to execute when vibrator is turned on
DEACTIVATE_COMMAND = ""  # Command to execute when vibrator is turned off

KILL_STRENGTH = 0.3  # Base kill vibration strength (0 to disable)
KILL_TIME = 1  # Kill vibration time

KILL_CRIT_STRENGTH_MULTIPLIER = 2.0  # Crit kill vibration multiplier
KILL_CRIT_TIME_MULTIPLIER = 1.0  # Crit kill time multiplier

# When at KILLSTREAK_MAX, vibration strength is KILL_STRENGTH * KILLSTREAK_STRENGTH_MULTIPLIER
# When you get first kill, vibration strength is KILL_STRENGTH * 1.0
KILLSTREAK_STRENGTH_MULTIPLIER = 2  # Amount that reaching KILLSTREAK_MAX should multiply strength
KILLSTREAK_TIME_MULTIPLIER = 1.5  # Amount that reaching KILLSTREAK_MAX should multiply time

KILLSTREAK_MAX = 20  # Max killstreak for scaling

DEATH_STRENGTH = 0.1  # Death vibration strength
DEATH_TIME = 1  # Death vibration time

UBER_ACTIVE_STRENGTH = 0.5  # Uber activation vibration strength (0 to disable)
UBER_STREAK_MULTIPLIER = 1.1  # Multipies uber strength by this per uber

UBER_MILESTONES = [25, 50, 75, 99]
UBER_MILESTONE_STRENGTH = 0.2  # Uber milestone passed vibration strength (0 to disable)
UBER_MILESTONE_TIME = 1  # Uber milestone vibration time

# When you pass the highest milestone, this will multiply UBER_MILESTONE_STRENGTH / UBER_MILESTONE_TIME
# When at the lowest milestone, multiplier will be only 1.0
UBER_MILESTONE_STRENGTH_MULTIPLIER = 1.0
UBER_MILESTONES_TIME_MULTIPLIER = 1.0  # See above

```

**Comment by MaxOhNoo** [comment]
running in 1920 x 1080 returns the same error.

**Comment by semper-lux** [comment]
This looks like an issue with your RCON. How did you launch the game, via the script or via steam?
